name: gridup_client
description: The client for the board game platform GridUP

version: 1.0.0+1

environment:
  sdk: ">=2.7.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.0+1
  cloud_functions: ^0.4.1+6
  get_it: ^3.0.3
  json_annotation: ^3.0.0
  state_persistence: ^0.0.7
  flutter_nfc_reader: ^0.1.0
  custom_navigator: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  json_serializable: ^3.2.3
  pedantic: 1.8.0+1

flutter:
  uses-material-design: true
  fonts:
    - family: Fira Code
      fonts:
        - asset: assets/fonts/Fira-Code/FiraCode-Light.ttf
          weight: 300
        - asset: assets/fonts/Fira-Code/FiraCode-Regular.ttf
          weight: 400
        - asset: assets/fonts/Fira-Code/FiraCode-Medium.ttf
          weight: 500
        - asset: assets/fonts/Fira-Code/FiraCode-Bold.ttf
          weight: 700
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product-Sans/Product-Sans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Product-Sans/Product-Sans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Product-Sans/Product-Sans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Product-Sans/Product-Sans-Bold-Italic.ttf
          weight: 700
          style: italic
    - family: icomoon
      fonts:
        - asset: assets/fonts/icomoon/icomoon.ttf
